# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       nokia-n900-configs
Summary:    Provides configs for Nokia N900
Version:    0.7.0
Release:    0
Group:      System/Device Mode Adaptation
License:    GPLv2
ExclusiveArch:  %{arm}
Source0:    nokia-n900-input-rules.conf
Source1:    nokia-n900-keys.map
Source2:    %{name}.sh
Source3:    nokia-n900-force-backlight.desktop
Source4:    n900-setbacklight.sh
Source5:    pipelines.conf
Source6:    n900-qt-mtf-config.sh
Source7:    %{name}.service
Source8:    getty@ttyO2.service
Source100:  nokia-n900-configs.yaml
Requires:   kbd
Requires(post): systemd
Requires(postun): systemd


%description
Provides configs for Nokia N900 device.



%prep
# No setup

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
install -D -m 644 %{SOURCE0} $RPM_BUILD_ROOT/etc/X11/xorg.conf.d/90-input-n900.conf
install -D -m 644 %{SOURCE1} $RPM_BUILD_ROOT/lib/kbd/keymaps/arm/qwerty/nokia-n900.map
install -D -m 644 %{SOURCE2} $RPM_BUILD_ROOT/usr/sbin/%{name}.sh
install -D -m 644 %{SOURCE3} $RPM_BUILD_ROOT/etc/xdg/autostart/n900-force-backlight.desktop
install -D -m 755 %{SOURCE4} $RPM_BUILD_ROOT/usr/bin/n900-setbacklight.sh
install -D -m 644 %{SOURCE5} $RPM_BUILD_ROOT/etc/camera/pipelines.conf
install -D -m 755 %{SOURCE6} $RPM_BUILD_ROOT/etc/profile.d/n900-qt-mtf-config.sh
install -D -m 644 %{SOURCE7} $RPM_BUILD_ROOT/lib/systemd/system/%{name}.service
install -d $RPM_BUILD_ROOT/lib/systemd/system/sysinit.target.wants/
ln -s ../%{name}.service $RPM_BUILD_ROOT/lib/systemd/system/sysinit.target.wants/%{name}.service
install -D -m 644 %{SOURCE8} $RPM_BUILD_ROOT/lib/systemd/system/getty@ttyO2.service
ln -s ../getty@ttyO2.service $RPM_BUILD_ROOT/lib/systemd/system/sysinit.target.wants/getty@ttyO2.service
# << install post



%post
# >> post
systemctl daemon-reload
# << post

%postun
# >> postun
systemctl daemon-reload
# << postun


%files
%defattr(-,root,root,-)
# >> files
%defattr(644,root,root,-)
# Input
%config %{_sysconfdir}/X11/xorg.conf.d/90-input-n900.conf
/lib/kbd/keymaps/arm/qwerty/nokia-n900.map
%attr(755,root,root) /usr/sbin/%{name}.sh
/lib/systemd/system/%{name}.service
/lib/systemd/system/sysinit.target.wants/%{name}.service
/lib/systemd/system/getty@ttyO2.service
/lib/systemd/system/sysinit.target.wants/getty@ttyO2.service
# Backlight
%attr(755,root,root) %{_bindir}/n900-setbacklight.sh
# Camera
%attr(644,root,root) %config %{_sysconfdir}/camera/pipelines.conf
# Misc
%attr(644,root,root) %config %{_sysconfdir}/xdg/autostart/n900-force-backlight.desktop
# N900 Qt & MTF configuration
%attr(755,root,root) %{_sysconfdir}/profile.d/n900-qt-mtf-config.sh
# << files


