# Makefile for Magenta's Kernel Components
# Copyright (c) 2012 Christina Brooks

obj-y	+= macho_loader.o
obj-y	+= mach.o
obj-y	+= ke_array.o
obj-y	+= ke_runtime.o
obj-y	+= darwin_getdirentries.o
obj-y	+= kext.o
obj-y	+= mach_kmsg.o